### ISSUE TITLE
Can't compile demo web server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zedalaye/delphionrails#13]
```
// I do not know much English

After cloning the source code I can not compile samples. Project files are 
missing madExcept, superobject, supertypes...
where to find them? or am I doing something wrong.

// I like the idea of creating DOR. I would like to be helpful



```

Original issue reported on code.google.com by `xabl.s...@gmail.com` on 3 May 2014 at 7:10

**Comment by zedalaye** [comment]
MadExcept has to be purchased, as its not required you could just remove units from .dpr. SuperObject can be found here : https://github.com/zedalaye/superobject
